- name: Pobieranie i modyfikacja kubeconfig
  hosts: masters
  become: yes
  tasks:
    - name: Czekaj na utworzenie pliku kubeconfig
      wait_for:
        path: /etc/rancher/rke2/rke2.yaml
        state: present
        timeout: 120

    - name: Zmiana uprawnień pliku kubeconfig
      file:
        path: /etc/rancher/rke2/rke2.yaml
        mode: '0644'

    - name: Pobieranie pliku kubeconfig
      fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: ./kubeconfig.yaml
        flat: yes

    - name: Przywrócenie uprawnień pliku kubeconfig
      file:
        path: /etc/rancher/rke2/rke2.yaml
        mode: '0600'

- name: Modyfikacja adresu serwera w kubeconfig
  hosts: localhost
  connection: local
  tasks:
    - name: Zamiana 127.0.0.1 na IP mastera
      replace:
        path: ./kubeconfig.yaml
        regexp: '127.0.0.1'
        replace: '172.26.255.144'